### ISSUE TITLE
Disable password based registration

### ISSUE THREAD

**Issue by marqh** [wmo-registers/codes-wmo-deploy#1]
A registry administrator shall be able to set a site wide configuration option to disable password based registration.

When this is set, a user accessing the login page should only be provided with the 'log|register in via Google'

**Comment by der** [comment]
Added support for additional registry configuration properties (so more can be added without a registry war rebuild) and included a property to suppress the UI for password-based login and registration.

**Comment by marqh** [comment]
fixed and tested on 
test.wmocodes.info

**Comment by marqh** [comment]
@dr-shorthair

i believe this feature is also useful for you.  it's available in 
https://github.com/UKGovLD/registry-config-base
now
