### ISSUE TITLE
contribute a translation

### ISSUE THREAD

**Issue by marqh** [wmo-registers/codes-wmo-deploy#17]
In the
< Contributing to codes.wmo >
section

provide information on how to propose an update adding a language translation to an existing entry

**Comment by Crocstar** [comment]
https://docs.google.com/document/d/1znNctQ3jHuFn94vWSPa640idJ1aeiLLLBfgf3rFir_Q/edit?usp=sharing

**Comment by marqh** [comment]
completd by #36
