### ISSUE TITLE
temporary password

### ISSUE THREAD

**Issue by marqh** [wmo-registers/codes-wmo-deploy#2]
Given #1 the functionality to create a temporary password, for use within the REST API shall exist.

Authenticated users shall be able to create a time limited temporary password for API authentication

**Comment by der** [comment]
Added UI to support this as an admin menu entry which only appears if normal password login is suppressed (and replaces the *change password* menu entry)

**Comment by marqh** [comment]
fixed and tested on 
test.wmocodes.info

**Comment by marqh** [comment]
@dr-shorthair

i believe this feature is also useful for you.  it's available in 
https://github.com/UKGovLD/registry-config-base
now
