### ISSUE TITLE
User guide: Overview 

### ISSUE THREAD

**Issue by Crocstar** [wmo-registers/codes-wmo-deploy#26]
Put this in about page (if it’s not already there):

Overview of WMO Codes Registry service
The primary purpose of the WMO Codes Registry is to support the new data exchange standard developed by WMO in support of Amendment 76 to ICAO Annex 3 "Meteorological Services for International Air Navigation". This new data exchange standard (WMO AvXML) enables exchange of operational aeronautical meteorological (OPMET) in XML format. It depends on availability of authoritative terms from WMO technical regulation - most notably WMO No. 306 Manual on Codes - as web-accessible resources that can be referenced from WMO AvXML- compliant data products.
The WMO Codes Registry is the mechanism through which the authoritative terms required for WMO AvXML are published as web-accessible resources.
The Met Office operates this Service on behalf of WMO as an “Initial Operating Capability” for the period of two (2) years from September 2013.

**Comment by marqh** [comment]
dealt with, to an extent; more work on  the expectations page will make this obsolete
