### ISSUE TITLE
User guide: content scope

### ISSUE THREAD

**Issue by Crocstar** [wmo-registers/codes-wmo-deploy#27]
Get rid:

WMO Codes Registry content scope
The initial set of authoritative terms published within the WMO Codes Registry is deemed sufficient to support the WMO AvXML data exchange standard.
The information provided within the WMO Codes Registry endeavours to be accurate, albeit sparse in comparison to the scope of the WMO Technical Regulation. Furthermore, please note that the Service does not (yet) provide a multi- lingual content, nor a change history of the authoritative terms pertaining to previous versions of the WMO Technical Regulation.
It is anticipated that the scope of content available through the WMO Codes Registry will expand during the Initial Operating Capability period; the content will be maintained by nominated members of WMO Expert Teams and the WMO Secretariat.
To request the provision of additional content from WMO Technical Regulation to be published via this Service please post to the WMO Codes List Registry group.

**Comment by marqh** [comment]
i agree, this is already captured in the 'expectations' page
