### ISSUE TITLE
User guide: Service support arrangements

### ISSUE THREAD

**Issue by Crocstar** [wmo-registers/codes-wmo-deploy#28]
Get rid (this is already in the about content): 

Service support arrangements and additional sources of information
The Met Office will endeavour that the Service is available, 24-hours per day, 7-days per week. In the event of a system fault, the Met Office will endeavour to restore the system to normal operation.
There is no provision of an alternative service should the Service be unavailable.
WMO provides a Google Group (WMO Codes List Registry) for discussion about the WMO Codes Registry and the content provided therein during the Initial Operating Capability period.
Limited end-user support is available via the Met Office help desk during UK business hours.
For technical information about the Registry software implementation and API, please refer to the documentation provided at the UKGovLD Registry project wiki. (note that the UKGovLD Registry software and API are open source and published under the Apache 2 license)
To notify the Service administrators of inappropriate or erroneous information, please post to the WMO Codes List Registry group or contact the Met Office help desk.

**Comment by marqh** [comment]
i agree, this is already captured in the 'expectations' page
