### ISSUE TITLE
data table for collections

### ISSUE THREAD

**Issue by marqh** [wmo-registers/codes-wmo-deploy#4]
When viewing a collection, a table view will be available, supporting pagination and in collection searching

http://test.wmocodes.info/grib2/codeflag/4.2
shall have a table, just as 
http://codes.wmo.int/grib2/codeflag/4.2
does in its 'table' tab

**Comment by der** [comment]
Added configurable support for display as datatables.

Should configure pageSize (in app.conf) to be higher than all reasonable registers for this to be useful.

**Comment by marqh** [comment]
fixed and tested on 
test.wmocodes.info
