### ISSUE TITLE
Search index

### ISSUE THREAD

**Issue by marqh** [wmo-registers/codes-wmo-deploy#5]
The search index shall be able to be rebuilt by an administrator

The main registry search will deliver results for rdfs:label values in the registry
http://test.wmocodes.info/ui/text-search?query=heat+index
should return
http://test.wmocodes.info/grib2/codeflag/4.2/0-0-12
at least

**Comment by der** [comment]
Unclear why the index isn't populated in the snapshot supplied.

Adding a new entry via the API (using the reinstated temporary password machinery) did correctly update the index.

Added an internal API operation to rebuild the text index from scratch, made it available as an administration menu item and documented it and how to a rebuild directly over the raw database files at: https://github.com/UKGovLD/registry-core/wiki/Operation#text-index

**Comment by marqh** [comment]
fixed and tested on 
test.wmocodes.info
